Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "rabbitmq1" do |rabbitmq1|
    rabbitmq1.vm.box = "ubuntu/bionic64"
    rabbitmq1.vm.hostname = 'rabbitmq1'
    rabbitmq1.vm.network :private_network, ip: "192.168.56.101"
    rabbitmq1.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"
    end

    rabbitmq1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "rabbitmq1"]
      v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
  end

  config.vm.define "rabbitmq2" do |rabbitmq2|
    rabbitmq2.vm.box = "ubuntu/bionic64"
    rabbitmq2.vm.hostname = 'db'

    rabbitmq2.vm.network :private_network, ip: "192.168.56.102"
    rabbitmq2.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"
    
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"
    end

    rabbitmq2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "rabbitmq2"]
      v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
  end

end